package away3d.test;

import flash.text.TextField;
import flash.text.TextFormat;
import flash.text.TextFieldAutoSize;


class ButtonState extends Sprite  {
	
	

	public function new(pwidth:Int, pheight:Int, ?text:String=null, ?color:Int=0) {
		// autogenerated
		super();
		
		OPPOSITE_OR[X | X] = N;
		OPPOSITE_OR[XY | X] = Y;
		OPPOSITE_OR[XZ | X] = Z;
		OPPOSITE_OR[XYZ | X] = YZ;
		OPPOSITE_OR[Y | Y] = N;
		OPPOSITE_OR[XY | Y] = X;
		OPPOSITE_OR[XYZ | Y] = XZ;
		OPPOSITE_OR[YZ | Y] = Z;
		OPPOSITE_OR[Z | Z] = N;
		OPPOSITE_OR[XZ | Z] = X;
		OPPOSITE_OR[XYZ | Z] = XY;
		OPPOSITE_OR[YZ | Z] = Y;
		SCALINGS[1] = [1, 1, 1];
		SCALINGS[2] = [-1, 1, 1];
		SCALINGS[4] = [-1, 1, -1];
		SCALINGS[8] = [1, 1, -1];
		SCALINGS[16] = [1, -1, 1];
		SCALINGS[32] = [-1, -1, 1];
		SCALINGS[64] = [-1, -1, -1];
		SCALINGS[128] = [1, -1, -1];
		
		addChild(new Panel(0, 0, pwidth, pheight));
		if ((text != null)) {
			var label:TextField = new TextField();
			label.autoSize = TextFieldAutoSize.LEFT;
			label.x = 5;
			label.y = 0;
			label.defaultTextFormat = new TextFormat("Arial", 14, color);
			label.text = text;
			addChild(label);
		}
	}

}

