package away3d.test;

import flash.text.TextField;
import flash.text.TextFormat;
import flash.text.TextFieldAutoSize;


class ButtonState extends Sprite  {
	
	

	public function new(pwidth:Int, pheight:Int, ?text:String=null, ?color:Int=0) {
		// autogenerated
		super();
		
		
		addChild(new Panel(0, 0, pwidth, pheight));
		if ((text != null)) {
			var label:TextField = new TextField();
			label.autoSize = TextFieldAutoSize.LEFT;
			label.x = 5;
			label.y = 0;
			label.defaultTextFormat = new TextFormat("Arial", 14, color);
			label.text = text;
			addChild(label);
		}
	}

}

