package away3d.core.block;

import away3d.core.draw.DrawPrimitive;


/**
 * Abstract primitive that can block other primitives from drawing
 */
class Blocker extends DrawPrimitive  {
	
	

	/**
	 * Return value signifies whether the given drawprimitive should be blocked. Called from the PrimitiveArray object on each blocker in the blockers array.
	 * 
	 * @see away3d.core.draw.PrimitiveArray
	 */
	public function block(pri:DrawPrimitive):Bool {
		
		return false;
	}

	// autogenerated
	public function new () {
		super();
		
	}

	

}

