package away3d.test;

import flash.display.Shape;
import flash.display.Graphics;


/**
 * Simple rounded rectangle panel
 */
class Panel extends Shape  {
	
	

	public function new(x:Int, y:Int, width:Int, height:Int, ?alpha:Float=0.3) {
		// autogenerated
		super();
		
		OPPOSITE_OR[X | X] = N;
		OPPOSITE_OR[XY | X] = Y;
		OPPOSITE_OR[XZ | X] = Z;
		OPPOSITE_OR[XYZ | X] = YZ;
		OPPOSITE_OR[Y | Y] = N;
		OPPOSITE_OR[XY | Y] = X;
		OPPOSITE_OR[XYZ | Y] = XZ;
		OPPOSITE_OR[YZ | Y] = Z;
		OPPOSITE_OR[Z | Z] = N;
		OPPOSITE_OR[XZ | Z] = X;
		OPPOSITE_OR[XYZ | Z] = XY;
		OPPOSITE_OR[YZ | Z] = Y;
		SCALINGS[1] = [1, 1, 1];
		SCALINGS[2] = [-1, 1, 1];
		SCALINGS[4] = [-1, 1, -1];
		SCALINGS[8] = [1, 1, -1];
		SCALINGS[16] = [1, -1, 1];
		SCALINGS[32] = [-1, -1, 1];
		SCALINGS[64] = [-1, -1, -1];
		SCALINGS[128] = [1, -1, -1];
		
		graphics.clear();
		graphics.lineStyle(1, 0x000000, 0.5, true);
		graphics.beginFill(0xBBBBCC, alpha);
		graphics.drawRoundRect(0, 0, width - 1, height - 1, 7, 7);
		this.x = x;
		this.y = y;
	}

}

