package away3d.core.traverse;

import flash.events.EventDispatcher;
import away3d.core.base.Object3D;
import away3d.core.light.ILightProvider;


/**
 * Traverser that gathers blocker primitives for occlusion culling.
 */
class LightTraverser extends Traverser  {
	
	

	/**
	 * Creates a new <code>LightTraverser</code> object.
	 */
	public function new() {
		// autogenerated
		super();
		
		
	}

	/**
	 * @inheritDoc
	 */
	public override function match(node:Object3D):Bool {
		
		if (!node.visible) {
			return false;
		}
		return true;
	}

	/**
	 * @inheritDoc
	 */
	public override function apply(node:Object3D):Void {
		//clear light arrays
		
		if (node.ownLights) {
			node.lightarray.clear();
		}
		if (Std.is(node, ILightProvider)) {
			(cast(node, ILightProvider)).light(node.parent.lightarray);
		}
	}

}

