package away3d.core.traverse;

import flash.events.EventDispatcher;
import away3d.core.base.Object3D;


/**
 * Traverser that gathers blocker primitives for occlusion culling.
 */
class SessionTraverser extends Traverser  {
	
	

	/**
	 * Creates a new <code>SessionTraverser</code> object.
	 */
	public function new() {
		// autogenerated
		super();
		
		
	}

	/**
	 * @inheritDoc
	 */
	public override function match(node:Object3D):Bool {
		
		if (!node.visible) {
			return false;
		}
		return true;
	}

	/**
	 * @inheritDoc
	 */
	public override function apply(node:Object3D):Void {
		
		node.updateSession();
	}

}

