package awaybuilder.camera;



class CameraZoom  {
	
	/**
	 * To precisely match up the render output with the Maya viewport the
	 * camera zoom value will have to be adjusted for different sizes.
	 */
	public static inline var MAYA_W720_H502:Float = 146.5;
	public static inline var DEFAULT:Float = 10;
	

	

	// autogenerated
	public function new () {
		
	}

	

}

