package awaybuilder.camera;



class CameraFocus  {
	
	public static inline var MAYA:Float = 5;
	public static inline var DEFAULT:Float = 100;
	

	

	// autogenerated
	public function new () {
		
	}

	

}

