package awaybuilder.collada;

import flash.events.Event;
import flash.net.URLLoader;


class ColladaLoader extends URLLoader  {
	public var collada(getCollada, null) : Xml;
	
	private var _collada:Xml;
	

	public function new() {
		// autogenerated
		super();
		
		
		this.addEventListener(Event.COMPLETE, this.onLoadComplete);
	}

	////////////////////////////////////////////////////////////////////////////////
	//
	// Event Handlers
	//
	////////////////////////////////////////////////////////////////////////////////
	private function onLoadComplete(event:Event):Void {
		
		this.removeEventListener(Event.COMPLETE, this.onLoadComplete);
		this._collada = ColladaUtil.removeNamespaces(this.data);
	}

	////////////////////////////////////////////////////////////////////////////////
	//
	// Getters and Setters
	//
	////////////////////////////////////////////////////////////////////////////////
	public function getCollada():Xml {
		
		return this._collada;
	}

}

