package away3d.core.utils;

import flash.utils.Dictionary;


class CacheStore  {
	
	public static var whiteShadingCache:Dictionary = new Dictionary(true);
	

	

	// autogenerated
	public function new () {
		
	}

	

}

