package away3d.core.utils;

import flash.events.EventDispatcher;
import flash.events.Event;


class ValueObject extends EventDispatcher  {
	
	private static var changed:Event;
	

	public function addOnChange(listener:Dynamic):Void {
		
		addEventListener("changed", listener, false, 0, true);
	}

	public function removeOnChange(listener:Dynamic):Void {
		
		removeEventListener("changed", listener, false);
	}

	private function notifyChange():Void {
		
		if (!hasEventListener("changed")) {
			return;
		}
		if (changed == null) {
			changed = new Event("changed");
		}
		dispatchEvent(changed);
	}

	// autogenerated
	public function new () {
		super();
		
	}

	

}

