package away3d.loaders.utils;

import away3d.core.utils.Debug;
import away3d.loaders.data.AnimationData;


/**
 * Store for all animations associated with an externally loaded file.
 */
class AnimationLibrary extends Hash<AnimationData>  {
	
	

	/**
	 * Adds an animation name reference to the library.
	 */
	public function addAnimation(name:String):AnimationData {
		//return if animation already exists
		
		if ((this.get(name) != null)) {
			return this.get(name);
		}
		var animationData:AnimationData = new AnimationData();
		animationData.name = name;
		this.set(name, animationData);
		return animationData;
	}

	/**
	 * Returns an animation data object for the given name reference in the library.
	 */
	public function getAnimation(name:String):AnimationData {
		//return if animation exists
		
		if ((this.get(name) != null)) {
			return this.get(name);
		}
		Debug.warning("Animation '" + name + "' does not exist");
		return null;
	}

	// autogenerated
	public function new () {
		super();
		
	}

	

}

