package awaybuilder;



class SceneSource  {
	
	public static inline var MAYA:String = "SceneSource.MAYA";
	public static inline var NATIVE:String = "SceneSource.NATIVE";
	

	

	// autogenerated
	public function new () {
		
	}

	

}

