package awaybuilder;



class CoordinateSystem  {
	
	public static inline var AFTER_EFFECTS:String = "CoordinateSystem.AFTER_EFFECTS";
	public static inline var MAYA:String = "CoordinateSystem.MAYA";
	public static inline var NATIVE:String = "CoordinateSystem.NATIVE";
	

	

	// autogenerated
	public function new () {
		
	}

	

}

