package away3d.core.base;

import away3d.core.geom.Plane3D;


class VertexClassification  {
	
	public var distance:Float;
	public var vertex:Vertex;
	public var plane:Plane3D;
	

	public function getDistance(val:Plane3D):Float {
		
		var d:Float = val.distance(vertex.position);
		if (d < 0 && !Math.isNaN(d)) {
			plane = val;
			distance = d;
		}
		return d;
	}

	// autogenerated
	public function new () {
		
	}

	

}

