package awaybuilder.abstracts;

import flash.events.EventDispatcher;
import awaybuilder.interfaces.IGeometryController;


class AbstractGeometryController extends EventDispatcher, implements IGeometryController {
	
	

	public function new() {
		// autogenerated
		super();
		
		
	}

	////////////////////////////////////////////////////////////////////////////////
	//
	// Public Methods
	//
	////////////////////////////////////////////////////////////////////////////////
	public function enableInteraction():Void {
		
	}

	public function disableInteraction():Void {
		
	}

}

