package away3d.core.project;

import flash.events.EventDispatcher;
import away3d.containers.View3D;
import flash.utils.Dictionary;
import away3d.core.utils.DofCache;
import away3d.core.utils.DrawPrimitiveStore;
import away3d.core.draw.IPrimitiveConsumer;
import away3d.core.draw.ScreenVertex;
import away3d.core.base.Object3D;
import away3d.cameras.lenses.ILens;
import away3d.core.draw.IPrimitiveProvider;
import flash.display.Sprite;
import away3d.core.math.Matrix3D;
import away3d.sprites.DofSprite2D;


class DofSpriteProjector implements IPrimitiveProvider {
	public var view(getView, setView) : View3D;
	
	private var _view:View3D;
	private var _vertexDictionary:Dictionary;
	private var _drawPrimitiveStore:DrawPrimitiveStore;
	private var _dofsprite:DofSprite2D;
	private var _lens:ILens;
	private var _dofcache:DofCache;
	private var _screenVertex:ScreenVertex;
	private var _persp:Float;
	

	public function getView():View3D {
		
		return _view;
	}

	public function setView(val:View3D):View3D {
		
		_view = val;
		_drawPrimitiveStore = view.drawPrimitiveStore;
		return val;
	}

	public function primitives(source:Object3D, viewTransform:Matrix3D, consumer:IPrimitiveConsumer):Void {
		
		_vertexDictionary = _drawPrimitiveStore.createVertexDictionary(source);
		_dofsprite = cast(source, DofSprite2D);
		_lens = _view.camera.lens;
		_screenVertex = _lens.project(viewTransform, _dofsprite.center);
		if (!_screenVertex.visible) {
			return;
		}
		_persp = view.camera.zoom / (1 + _screenVertex.z / view.camera.focus);
		_screenVertex.z += _dofsprite.deltaZ;
		_dofcache = DofCache.getDofCache(_dofsprite.bitmap);
		consumer.primitive(_drawPrimitiveStore.createDrawScaledBitmap(source, _screenVertex, _dofsprite.smooth, _dofcache.getBitmap(_screenVertex.z), _persp * _dofsprite.scaling, _dofsprite.rotation));
	}

	// autogenerated
	public function new () {
		
	}

	

}

