package away3d.loaders.data;

import away3d.core.math.Matrix3D;


/**
 * Data class for a bone used in SkinAnimation.
 */
class BoneData extends ContainerData  {
	
	/**
	 * Transform information for the joint in a SkinAnimation
	 */
	public var jointTransform:Matrix3D;
	

	

	// autogenerated
	public function new () {
		super();
		this.jointTransform = new Matrix3D();
		
	}

	

}

