package awaybuilder.utils;



class CoordinateCopy  {
	
	public static inline var X:String = "x";
	public static inline var Y:String = "y";
	public static inline var Z:String = "z";
	public static inline var ROTATION_X:String = "rotationX";
	public static inline var ROTATION_Y:String = "rotationY";
	public static inline var ROTATION_Z:String = "rotationZ";
	public static inline var SCALE_X:String = "scaleX";
	public static inline var SCALE_Y:String = "scaleY";
	public static inline var SCALE_Z:String = "scaleZ";
	

	public static function position(source:Dynamic, target:Dynamic):Void {
		
		target[CoordinateCopy.X] = source[CoordinateCopy.X];
		target[CoordinateCopy.Y] = source[CoordinateCopy.Y];
		target[CoordinateCopy.Z] = source[CoordinateCopy.Z];
	}

	public static function rotation(source:Dynamic, target:Dynamic):Void {
		
		target[CoordinateCopy.ROTATION_X] = source[CoordinateCopy.ROTATION_X];
		target[CoordinateCopy.ROTATION_Y] = source[CoordinateCopy.ROTATION_Y];
		target[CoordinateCopy.ROTATION_Z] = source[CoordinateCopy.ROTATION_Z];
	}

	public static function scale(source:Dynamic, target:Dynamic):Void {
		
		target[CoordinateCopy.SCALE_X] = source[CoordinateCopy.SCALE_X];
		target[CoordinateCopy.SCALE_Y] = source[CoordinateCopy.SCALE_Y];
		target[CoordinateCopy.SCALE_Z] = source[CoordinateCopy.SCALE_Z];
	}

	// autogenerated
	public function new () {
		
		OPPOSITE_OR[X | X] = N;
		OPPOSITE_OR[XY | X] = Y;
		OPPOSITE_OR[XZ | X] = Z;
		OPPOSITE_OR[XYZ | X] = YZ;
		OPPOSITE_OR[Y | Y] = N;
		OPPOSITE_OR[XY | Y] = X;
		OPPOSITE_OR[XYZ | Y] = XZ;
		OPPOSITE_OR[YZ | Y] = Z;
		OPPOSITE_OR[Z | Z] = N;
		OPPOSITE_OR[XZ | Z] = X;
		OPPOSITE_OR[XYZ | Z] = XY;
		OPPOSITE_OR[YZ | Z] = Y;
		SCALINGS[1] = [1, 1, 1];
		SCALINGS[2] = [-1, 1, 1];
		SCALINGS[4] = [-1, 1, -1];
		SCALINGS[8] = [1, 1, -1];
		SCALINGS[16] = [1, -1, 1];
		SCALINGS[32] = [-1, -1, 1];
		SCALINGS[64] = [-1, -1, -1];
		SCALINGS[128] = [1, -1, -1];
	}

	

}

