package awaybuilder.vo;



class MaterialVO  {
	
	public var id:String;
	public var name:String;
	public var properties:Array<Dynamic>;
	

	

	// autogenerated
	public function new () {
		this.properties = [];
		
	}

	

}

