package awaybuilder.vo;



class SceneObjectVO  {
	
	public var x:Float;
	public var y:Float;
	public var z:Float;
	public var rotationX:Float;
	public var rotationY:Float;
	public var rotationZ:Float;
	public var scaleX:Float;
	public var scaleY:Float;
	public var scaleZ:Float;
	

	

	// autogenerated
	public function new () {
		this.x = 0;
		this.y = 0;
		this.z = 0;
		this.rotationX = 0;
		this.rotationY = 0;
		this.rotationZ = 0;
		this.scaleX = 1;
		this.scaleY = 1;
		this.scaleZ = 1;
		
	}

	

}

