package away3d.core.project;



class ProjectorType  {
	
	public static inline var CONVEX_BLOCK:String = "ConvexBlock";
	public static inline var DIR_SPRITE:String = "DirSprite";
	public static inline var DOF_SPRITE:String = "DofSprite";
	public static inline var MESH:String = "Mesh";
	public static inline var MOVIE_CLIP_SPRITE:String = "MovieClipSprite";
	public static inline var OBJECT_CONTAINER:String = "ObjectContainer";
	public static inline var SPRITE:String = "Sprite";
	

	

	// autogenerated
	public function new () {
		
	}

	

}

